controller_list:
  - name: fake_first_manipulator_controller
    joints:
      - h1_joint_s
      - h1_joint_l
      - h1_joint_e
      - h1_joint_u
      - h1_joint_r
      - h1_joint_b
      - h1_joint_t
  - name: fake_second_manipulator_controller
    joints:
      - h2_joint_s
      - h2_joint_l
      - h2_joint_e
      - h2_joint_u
      - h2_joint_r
      - h2_joint_b
      - h2_joint_t
  - name: fake_dual_manipulator_controller
    joints:
      - h1_joint_s
      - h1_joint_l
      - h1_joint_e
      - h1_joint_u
      - h1_joint_r
      - h1_joint_b
      - h1_joint_t
      - h2_joint_s
      - h2_joint_l
      - h2_joint_e
      - h2_joint_u
      - h2_joint_r
      - h2_joint_b
      - h2_joint_t