// Generated by gencpp from file mouse_reader/mousemove.msg
// DO NOT EDIT!


#ifndef MOUSE_READER_MESSAGE_MOUSEMOVE_H
#define MOUSE_READER_MESSAGE_MOUSEMOVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Bool.h>
#include <std_msgs/Bool.h>
#include <std_msgs/Bool.h>
#include <geometry_msgs/Point.h>

namespace mouse_reader
{
template <class ContainerAllocator>
struct mousemove_
{
  typedef mousemove_<ContainerAllocator> Type;

  mousemove_()
    : header()
    , left()
    , middle()
    , right()
    , move()  {
    }
  mousemove_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(_alloc)
    , middle(_alloc)
    , right(_alloc)
    , move(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _middle_type;
  _middle_type middle;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _right_type;
  _right_type right;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _move_type;
  _move_type move;




  typedef boost::shared_ptr< ::mouse_reader::mousemove_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mouse_reader::mousemove_<ContainerAllocator> const> ConstPtr;

}; // struct mousemove_

typedef ::mouse_reader::mousemove_<std::allocator<void> > mousemove;

typedef boost::shared_ptr< ::mouse_reader::mousemove > mousemovePtr;
typedef boost::shared_ptr< ::mouse_reader::mousemove const> mousemoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mouse_reader::mousemove_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mouse_reader::mousemove_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mouse_reader

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'mouse_reader': ['/home/tudeng/lucindra-RoboTech/src/mouse_reader/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mouse_reader::mousemove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mouse_reader::mousemove_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mouse_reader::mousemove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mouse_reader::mousemove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mouse_reader::mousemove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mouse_reader::mousemove_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mouse_reader::mousemove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a83e60f7318953a6c4c6463003ed1a9";
  }

  static const char* value(const ::mouse_reader::mousemove_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a83e60f7318953aULL;
  static const uint64_t static_value2 = 0x6c4c6463003ed1a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::mouse_reader::mousemove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mouse_reader/mousemove";
  }

  static const char* value(const ::mouse_reader::mousemove_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mouse_reader::mousemove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
std_msgs/Bool left\n\
std_msgs/Bool middle\n\
std_msgs/Bool right\n\
geometry_msgs/Point move\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::mouse_reader::mousemove_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mouse_reader::mousemove_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.middle);
      stream.next(m.right);
      stream.next(m.move);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mousemove_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mouse_reader::mousemove_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mouse_reader::mousemove_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    s << indent << "middle: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.middle);
    s << indent << "right: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
    s << indent << "move: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.move);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOUSE_READER_MESSAGE_MOUSEMOVE_H
